# justfile

prepare-max:
    cargo run --bin prepare -- --rules-repo https://github.com/Yara-Rules/rules --samples 200 --hit-rate 0.1 --fetch-eicar --force

prepare:
    cargo run --bin prepare

run:
    cargo run --release

bench:
    cargo bench

test:
    cargo test

clean:
    cargo clean
