name: Complete Mirror

on:
    push:
    schedule:
        - cron: "0 2 * * *"

jobs:
    mirror:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout with full history
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Complete mirror
              env:
                  DESTINATION_REPO: ${{ secrets.DESTINATION_REPO }}
                  DESTINATION_TOKEN: ${{ secrets.DESTINATION_TOKEN }}
              run: |
                  git remote add destination https://${DESTINATION_TOKEN}@${DESTINATION_REPO}
                  git push destination --mirror
