name: Mirror Repository (Using Action)

on:
  push:
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.TARGET_REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 