name: Complete Mirror

on:
    push:
    schedule:
        - cron: "0 2 * * *"

jobs:
    mirror:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout with full history
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Complete mirror
              run: |
                  git remote add destination https://${DESTINATION_TOKEN}@${DESTINATION_REPO#https://}
                  git push destination --mirror  # Pousse TOUT
