name: Sync Issues to Repo B

on:
    issues:
        types: [opened, edited, reopened, closed]

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync issue to Repo B
              uses: peter-evans/issue-sync@v2
              with:
                  source: ${{ github.repository }}
                  target: https://github.com/EpitechPromo2027/G-EIP-600-REN-6-1-eip-alexis.boitel
                  github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  labels: true
                  state: true
                  comments: true

        #   - name: Add synced issue to GitHub Project
        #     uses: actions/github-script@v7
        #     with:
        #       github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        #       script: |
        #         const issue = context.payload.issue;

        #         // Get the target issue we just created in Repo B
        #         const targetOwner = "your-org";
        #         const targetRepo = "RepoB";
        #         const { data: issues } = await github.rest.issues.listForRepo({
        #           owner: targetOwner,
        #           repo: targetRepo,
        #           state: "all",
        #           per_page: 1,
        #           sort: "created",
        #           direction: "desc"
        #         });

        #         const targetIssue = issues[0]; // latest synced issue

        #         // Use GraphQL to add it to Project
        #         const PROJECT_ID = "PVT_xxxxxxxxx"; // <-- replace with your project ID
        #         const contentId = targetIssue.node_id;

        #         await github.graphql(
        #           `mutation($project:ID!, $content:ID!) {
        #             addProjectV2ItemById(input: {projectId: $project, contentId: $content}) {
        #               item { id }
        #             }
        #           }`,
        #           { project: PROJECT_ID, content: contentId }
        #         );
