name: Sync Issues to Repo B

on:
    issues: # Trigger on new issues
        types: [opened, edited, closed, reopened]
    issue_comment:
        types: [created]

env:
    GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Ideally a PAT with write access to both repos

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Run Issue Sync Action
              uses: Maximisch/issue-sync-action@v2.0
              with:
                  target_repo: "EpitechPromo2027/G-EIP-600-REN-6-1-eip-alexis.boitel"
                  only_sync_on_label: "" # Optional: specify a label to filter
                  only_sync_main_issue: "false" # Set "true" if you don't want to sync comments
                  source_url: "" # Optional override of API endpoint
                  target_url: "api.github.com" # Defaults to GitHub Cloud
                  source_pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  target_pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
